server:
  port: 8081
spring:
  application:
    name: OnlyOne
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/only?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    username: Nina
    password: 123456
    port: 5672
    virtual-host: /
    #生成者确认机制
    publisher-confirm-type: correlated
    publisher-returns: true #消息回调

    template:
      mandatory: true #到达队列失败触发回调函数
      retry:
        enabled: true            # 发送失败时重试
        initial-interval: 1000   # 初始重试间隔
        multiplier: 1.5          # 重试倍数
        max-attempts: 3          # 最大重试次数
    listener:
      type: simple
      simple:
        acknowledge-mode: manual  # 或 消息主动确认
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liJ1yyBUbZHqY7Le
            client-secret: 48351af23c7e6effd30cb38107f0910b872cef8b
            scope: user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: github
            provider: github
        provider:
          github:
            #认证地址
            authorization-uri: https://github.com/login/oauth/authorize
            #获取token的地址
            token-uri: https://github.com/login/oauth/access_token
            #获取用户信息的地址
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
  mail:
    host: smtp.qq.com
    port: 587
    username: 3550478009@qq.com
    password: ytzilplmjcfndbbj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



mybatis-plus:
  type-aliases-package: com.example.onlyone.entity # 别名扫描包
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: update-images